[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = G28_SOG1_2026
db_name = False
db_maxconn = 64
admin_passwd = admin_G28_2026
logfile = /var/log/odoo/odoo.log
log_level = info
